# Generated by Django 4.1.1 on 2022-10-19 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
